### PR TITLE
Added QuickSort code in Java

### PR DESCRIPTION
**Pull request by Kavs-123**

### CODE REVIEW

**Comment by aman-raza** [comment]
create a pr without deleting the files

**Comment by Kavs-123** [comment]
> create a pr without deleting the files

Is this project excluded from Hacktoberfest2021 @aman-raza ??

**Comment by aman-raza** [comment]
is this showing to you?

**Comment by aman-raza** [comment]
I guess it has been removed, they are removing repositories that are easy to contribute to

**Comment by Kavs-123** [comment]
> is this showing to you?

image

**Comment by Kavs-123** [comment]
> > is this showing to you?
> 
> image

this is getting reflected there

**Comment by Kavs-123** [comment]
> > > is this showing to you?
> > 
> > 
> > image
> 
> this is getting reflected there

it means my other 2 PRs too will show excluded ?? @aman-raza

**Comment by aman-raza** [comment]
ya sorry for that

**Pull request closed without merging**
